version: '3.9'
name: 'filters'
services:

  date_filter_barrier:
    build:
      context: ./
      dockerfile: ./controllers/barrier/Dockerfile
    container_name: date_filter_barrier
    image: barrier:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=date_filter
      - FILTER_COUNT=3
      - LOGGING_LEVEL=DEBUG
    networks:
      - tp1_testing_net

  date_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/date_filter/Dockerfile
    container_name: date_filter1
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/date_filter/config.ini:/config.ini

  date_filter2:
    build:
      context: ./
      dockerfile: ./controllers/filters/date_filter/Dockerfile
    container_name: date_filter2
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
      - FILTER_NUMBER=2
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/date_filter/config.ini:/config.ini

  date_filter3:
    build:
      context: ./
      dockerfile: ./controllers/filters/date_filter/Dockerfile
    container_name: date_filter3
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
      - FILTER_NUMBER=3
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/date_filter/config.ini:/config.ini

  category_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/category_filter/Dockerfile
    container_name: category_filter1
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/category_filter/config.ini:/config.ini
    
  category_filter2:
    build:
      context: ./
      dockerfile: ./controllers/filters/category_filter/Dockerfile
    container_name: category_filter2
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/category_filter/config.ini:/config.ini

  category_filter3:
    build:
      context: ./
      dockerfile: ./controllers/filters/category_filter/Dockerfile
    container_name: category_filter3
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/category_filter/config.ini:/config.ini

  title_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/title_filter/Dockerfile
    container_name: title_filter1
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/title_filter/config.ini:/config.ini
      
  title_filter2:
    build:
      context: ./
      dockerfile: ./controllers/filters/title_filter/Dockerfile
    container_name: title_filter2
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/title_filter/config.ini:/config.ini

  title_filter3:
    build:
      context: ./
      dockerfile: ./controllers/filters/title_filter/Dockerfile
    container_name: title_filter3
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/title_filter/config.ini:/config.ini

networks:
  tp1_testing_net:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
