version: '3.9'
name: 'filters'
services:
  date_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/date_filter/Dockerfile
    container_name: date_filter1
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=date_filter1
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  date_filter2:
    build:
      context: ./
      dockerfile: ./controllers/filters/date_filter/Dockerfile
    container_name: date_filter2
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=date_filter2
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  date_filter3:
    build:
      context: ./
      dockerfile: ./controllers/filters/date_filter/Dockerfile
    container_name: date_filter3
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=date_filter3
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  category_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/category_filter/Dockerfile
    container_name: category_filter1
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - CATEGORY=Computers
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=category_filter1
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  category_filter2:
    build:
      context: ./
      dockerfile: ./controllers/filters/category_filter/Dockerfile
    container_name: category_filter2
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - CATEGORY=Computers
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=category_filter2
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  category_filter3:
    build:
      context: ./
      dockerfile: ./controllers/filters/category_filter/Dockerfile
    container_name: category_filter3
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - CATEGORY=Computers
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=category_filter3
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  title_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/title_filter/Dockerfile
    container_name: title_filter1
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=title_filter1
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  title_filter2:
    build:
      context: ./
      dockerfile: ./controllers/filters/title_filter/Dockerfile
    container_name: title_filter2
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=title_filter2
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

  title_filter3:
    build:
      context: ./
      dockerfile: ./controllers/filters/title_filter/Dockerfile
    container_name: title_filter3
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=title_filter3
      - ITEMS_PER_BATCH=100
    networks:
      - tp1_testing_net

networks:
  tp1_testing_net:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
