version: '3.9'
name: 'filters'
services:

  title_filter_barrier:
    build:
      context: ./
      dockerfile: ./controllers/barrier/Dockerfile
    container_name: title_filter_barrier
    image: barrier:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=title_filter
      - FILTER_COUNT=1
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/barrier/main.py:/main.py

  title_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/title_filter/Dockerfile
    container_name: title_filter1
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/title_filter/config.ini:/config.ini
      - ./controllers/filters/title_filter/main.py:/main.py

  date_filter_barrier:
    build:
      context: ./
      dockerfile: ./controllers/barrier/Dockerfile
    container_name: date_filter_barrier
    image: barrier:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=date_filter
      - FILTER_COUNT=1
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/barrier/main.py:/main.py

  date_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/date_filter/Dockerfile
    container_name: date_filter1
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/date_filter/config.ini:/config.ini
      - ./controllers/filters/date_filter/main.py:/main.py

  category_filter_barrier:
    build:
      context: ./
      dockerfile: ./controllers/barrier/Dockerfile
    container_name: category_filter_barrier
    image: barrier:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=category_filter
      - FILTER_COUNT=1
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/barrier/main.py:/main.py

  category_filter1:
    build:
      context: ./
      dockerfile: ./controllers/filters/category_filter/Dockerfile
    container_name: category_filter1
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/category_filter/config.ini:/config.ini
      - ./controllers/filters/category_filter/main.py:/main.py

  decade_counter:
    build:
      context: ./
      dockerfile: ./controllers/filters/decade_counter/Dockerfile
    container_name: decade_counter
    image: decade_counter:latest
    entrypoint: python3 main.py
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/decade_counter/config.ini:/config.ini
      - ./controllers/filters/decade_counter/main.py:/main.py
  sentiment_analyzer_barrier:
    build:
      context: ./
      dockerfile: ./controllers/barrier/Dockerfile
    container_name: sentiment_analyzer_barrier
    image: barrier:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=sentiment_analyzer
      - FILTER_COUNT=6
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/barrier/main.py:/main.py

  sentiment_analyzer1:
    build:
      context: ./
      dockerfile: ./controllers/filters/sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer1
    image: sentiment_analyzer:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/sentiment_analyzer/config.ini:/config.ini
      - ./controllers/filters/sentiment_analyzer/main.py:/main.py

  sentiment_analyzer2:
    build:
      context: ./
      dockerfile: ./controllers/filters/sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer2
    image: sentiment_analyzer:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=2
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/sentiment_analyzer/config.ini:/config.ini
      - ./controllers/filters/sentiment_analyzer/main.py:/main.py

  sentiment_analyzer3:
    build:
      context: ./
      dockerfile: ./controllers/filters/sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer3
    image: sentiment_analyzer:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=3
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/sentiment_analyzer/config.ini:/config.ini
      - ./controllers/filters/sentiment_analyzer/main.py:/main.py

  sentiment_analyzer4:
    build:
      context: ./
      dockerfile: ./controllers/filters/sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer4
    image: sentiment_analyzer:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=4
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/sentiment_analyzer/config.ini:/config.ini
      - ./controllers/filters/sentiment_analyzer/main.py:/main.py

  sentiment_analyzer5:
    build:
      context: ./
      dockerfile: ./controllers/filters/sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer5
    image: sentiment_analyzer:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=5
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/sentiment_analyzer/config.ini:/config.ini
      - ./controllers/filters/sentiment_analyzer/main.py:/main.py

  sentiment_analyzer6:
    build:
      context: ./
      dockerfile: ./controllers/filters/sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer6
    image: sentiment_analyzer:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=6
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/sentiment_analyzer/config.ini:/config.ini
      - ./controllers/filters/sentiment_analyzer/main.py:/main.py

  joiner:
    build:
      context: ./
      dockerfile: ./controllers/filters/joiner/Dockerfile
    container_name: joiner
    image: joiner:latest
    entrypoint: python3 main.py
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/joiner/config.ini:/config.ini
      - ./controllers/filters/joiner/main.py:/main.py

  review_counter:
    build:
      context: ./
      dockerfile: ./controllers/filters/review_counter/Dockerfile
    container_name: review_counter
    image: review_counter:latest
    entrypoint: python3 main.py
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/review_counter/config.ini:/config.ini
      - ./controllers/filters/review_counter/main.py:/main.py

  sentiment_average_reducer:
    build:
      context: ./
      dockerfile: ./controllers/filters/sentiment_average_reducer/Dockerfile
    container_name: sentiment_average_reducer
    image: sentiment_average_reducer:latest
    entrypoint: python3 main.py
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/filters/sentiment_average_reducer/config.ini:/config.ini
      - ./controllers/filters/sentiment_average_reducer/main.py:/main.py

networks:
  tp1_testing_net:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
