version: '3.9'
name: 'filters'
services:

  boundary:
    build:
      context: ./
      dockerfile: ./src/boundary/Dockerfile
    container_name: boundary
    image: boundary:latest
    entrypoint: python3 boundary.py
    networks:
      - tp1_testing_net
    ports:
      - "8080:8080"
    volumes:
      - ./src/boundary/config.ini:/config.ini
      - ./src/boundary/boundary.py:/boundary.py

  title_filter_proxy:
    build:
      context: ./
      dockerfile: ./src/controllers/proxy/Dockerfile
    container_name: title_filter_proxy
    image: proxy:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=title_filter
      - FILTER_COUNT=2
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/proxy/main.py:/main.py

  title_filter1:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/title_filter/Dockerfile
    container_name: title_filter1
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/title_filter/config.ini:/config.ini
      - ./src/controllers/filters/title_filter/main.py:/main.py
      - ./state/title_filter1/:/state

  title_filter2:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/title_filter/Dockerfile
    container_name: title_filter2
    image: title_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=2
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/title_filter/config.ini:/config.ini
      - ./src/controllers/filters/title_filter/main.py:/main.py
      - ./state/title_filter2/:/state

  date_filter_proxy:
    build:
      context: ./
      dockerfile: ./src/controllers/proxy/Dockerfile
    container_name: date_filter_proxy
    image: proxy:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=date_filter
      - FILTER_COUNT=2
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/proxy/main.py:/main.py

  date_filter1:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/date_filter/Dockerfile
    container_name: date_filter1
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/date_filter/config.ini:/config.ini
      - ./src/controllers/filters/date_filter/main.py:/main.py
      - ./state/date_filter1/:/state

  date_filter2:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/date_filter/Dockerfile
    container_name: date_filter2
    image: date_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=2
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/date_filter/config.ini:/config.ini
      - ./src/controllers/filters/date_filter/main.py:/main.py
      - ./state/date_filter2/:/state

  category_filter_proxy:
    build:
      context: ./
      dockerfile: ./src/controllers/proxy/Dockerfile
    container_name: category_filter_proxy
    image: proxy:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=category_filter
      - FILTER_COUNT=1
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/proxy/main.py:/main.py

  category_filter1:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/category_filter/Dockerfile
    container_name: category_filter1
    image: category_filter:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/category_filter/config.ini:/config.ini
      - ./src/controllers/filters/category_filter/main.py:/main.py
      - ./state/category_filter1/:/state

  review_counter_proxy:
    build:
      context: ./
      dockerfile: ./src/controllers/proxy/Dockerfile
    container_name: review_counter_proxy
    image: proxy:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=review_counter
      - FILTER_COUNT=1
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/proxy/main.py:/main.py

  decade_counter1:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/decade_counter/Dockerfile
    container_name: decade_counter1
    image: decade_counter:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/decade_counter/config.ini:/config.ini
      - ./src/controllers/filters/decade_counter/main.py:/main.py
      - ./state/decade_counter1/:/state
      
  sentiment_analyzer_proxy:
    build:
      context: ./
      dockerfile: ./src/controllers/proxy/Dockerfile
    container_name: sentiment_analyzer_proxy
    image: proxy:latest
    entrypoint: python3 main.py
    environment:
      - FILTER_TYPE=sentiment_analyzer
      - FILTER_COUNT=1
      - LOGGING_LEVEL=INFO
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/proxy/main.py:/main.py

  sentiment_analyzer1:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer1
    image: sentiment_analyzer:latest
    entrypoint: python3 main.py
    environment:
      - ITEMS_PER_BATCH=700
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/sentiment_analyzer/config.ini:/config.ini
      - ./src/controllers/filters/sentiment_analyzer/main.py:/main.py
      - ./state/sentiment_analyzer1/:/state

  review_joiner1:
    build:
      context: ./
      dockerfile: ./src/controllers/review_joiner/Dockerfile
    container_name: review_joiner1
    image: review_joiner:latest
    entrypoint: python3 review_joiner.py
    environment:
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/review_joiner/config.ini:/config.ini
      - ./src/controllers/review_joiner/review_joiner.py:/review_joiner.py
      - ./state/review_joiner1/:/state

  review_counter1:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/review_counter/Dockerfile
    container_name: review_counter1
    image: review_counter:latest
    entrypoint: python3 review_counter.py
    environment:
      - FILTER_NUMBER=1
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/review_counter/config.ini:/config.ini
      - ./src/controllers/filters/review_counter/review_counter.py:/review_counter.py
      - ./state/review_counter1/:/state

  sentiment_average_reducer:
    build:
      context: ./
      dockerfile: ./src/controllers/filters/sentiment_average_reducer/Dockerfile
    container_name: sentiment_average_reducer
    image: sentiment_average_reducer:latest
    entrypoint: python3 main.py
    networks:
      - tp1_testing_net
    volumes:
      - ./src/controllers/filters/sentiment_average_reducer/config.ini:/config.ini
      - ./src/controllers/filters/sentiment_average_reducer/main.py:/main.py

networks:
  tp1_testing_net:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
