
version: '3.9'
name: 'tp1'
services:

  # rabbit:
  #   container_name: rabbit
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   networks:
  #     - testing_net

  boundary:
    container_name: boundary
    image: boundary:latest
    entrypoint: python3 main.py --books books.csv --reviews reviews.csv
    environment:
      - LOGGING_LEVEL=DEBUG
    networks:
      - tp1_testing_net
    volumes:
      - ./boundary.py:/main.py
      - ./controllers/io/input_controller.py:/controllers/io/input_controller.py
      - ./controllers/io/output_controller.py:/controllers/io/output_controller.py
      - ./messaging/goutong.py:/messaging/goutong.py
      - ./data/books_data.csv:/books.csv
      - ./data/Books_ratings.csv:/reviews.csv

  q1_filter1:
    container_name: q1_filter1
    image: q1_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - CATEGORY=Computers
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=q1_filter1
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/q1_filter/main.py:/main.py
      - ./messaging/goutong.py:/messaging/goutong.py

  q1_filter2:
    container_name: q1_filter2
    image: q1_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - CATEGORY=Computers
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=q1_filter2
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/q1_filter/main.py:/main.py
      - ./messaging/goutong.py:/messaging/goutong.py

  q1_filter3:
    container_name: q1_filter3
    image: q1_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - CATEGORY=Computers
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=q1_filter3
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/q1_filter/main.py:/main.py
      - ./messaging/goutong.py:/messaging/goutong.py

  q1_filter4:
    container_name: q1_filter4
    image: q1_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - CATEGORY=Computers
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=q1_filter4
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/q1_filter/main.py:/main.py
      - ./messaging/goutong.py:/messaging/goutong.py

  q1_filter5:
    container_name: q1_filter5
    image: q1_filter:latest
    entrypoint: python3 main.py
    environment:
      - LOWER_BOUND=2000
      - UPPER_BOUND=2023
      - CATEGORY=Computers
      - TITLE_KEYWORD=distributed
      - LOGGING_LEVEL=INFO
      - FILTER_NAME=q1_filter5
    networks:
      - tp1_testing_net
    volumes:
      - ./controllers/q1_filter/main.py:/main.py
      - ./messaging/goutong.py:/messaging/goutong.py

networks:
  tp1_testing_net:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
